In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
 import cv2

In [3]:
img = cv2.imread("C:\\Users\\KRUPA\\Documents\\SGP\\krupa.jpeg",1)

In [4]:
print((img))

[[[236 210 173]
  [236 210 173]
  [236 210 173]
  ...
  [242 207 163]
  [242 207 163]
  [242 207 163]]

 [[236 210 173]
  [236 210 173]
  [236 210 173]
  ...
  [242 207 163]
  [242 207 163]
  [242 207 163]]

 [[236 210 173]
  [236 210 173]
  [236 210 173]
  ...
  [242 207 163]
  [242 207 163]
  [242 207 163]]

 ...

 [[ 28  66  78]
  [ 28  66  78]
  [ 27  64  78]
  ...
  [ 77 164 184]
  [ 77 164 184]
  [ 77 164 184]]

 [[ 29  67  79]
  [ 26  66  78]
  [ 25  64  78]
  ...
  [ 77 164 184]
  [ 77 164 184]
  [ 77 164 184]]

 [[ 27  67  79]
  [ 26  66  78]
  [ 25  65  77]
  ...
  [ 75 162 182]
  [ 75 162 182]
  [ 75 162 182]]]


In [5]:
print(img.shape)

(633, 699, 3)


In [6]:
cv2.imshow("new",img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [7]:
resized = cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("new",resized)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [8]:
#create cascade classifier object
face_cascade = cv2.CascadeClassifier("C:\\Users\\KRUPA\\Documents\\SGP\\haarcascade_frontalface_default.xml")
#reading img as gray scale img
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
#search co ordinates of img
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05, minNeighbors=5)

In [9]:
print(type(faces))

<class 'numpy.ndarray'>


In [10]:
print(faces)

[[296 247 166 166]]


In [11]:
# add rectangle face arround it
for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y) , (x+y,y+h),(0,255,0),3)

In [12]:
resized = cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("new",resized)
cv2.waitKey(0)
cv2.destroyAllWindows()