In [18]:
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
import numpy as np

In [3]:
import os

In [4]:
DIRECTORY = r"C:\Mask Detection\CODE\Face-Mask-Detection-master\dataset"
CATEGORIES = ["with_mask", "without_mask"]

In [5]:
data = []
labels = []

for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category) #os.path will be used to find out path
    for img in os.listdir(path): #list down all images in particular folder
    	img_path = os.path.join(path, img) 
    	image = load_img(img_path, target_size=(224, 224)) #load the image
    	image = img_to_array(image) #covert the image to array
    	image = preprocess_input(image)

C:\Users\KRUPA\anaconda3\lib\site-packages\PIL\Image.py:932: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


In [6]:
data.append(image)
labels.append(category)

In [7]:
print(image)

[[[ 0.90588236  0.8980392   0.88235295]
  [ 0.8901961   0.85882354  0.8509804 ]
  [ 0.9137255   0.84313726  0.8509804 ]
  ...
  [ 0.427451    0.5529412   0.81960785]
  [ 0.36470592  0.5137255   0.77254903]
  [ 0.30980396  0.45882356  0.7176471 ]]

 [[ 0.75686276  0.75686276  0.7411765 ]
  [ 0.8509804   0.84313726  0.827451  ]
  [ 0.9607843   0.9137255   0.9137255 ]
  ...
  [ 0.8745098   0.73333335  1.        ]
  [ 0.77254903  0.6313726   1.        ]
  [ 0.6392157   0.5137255   0.88235295]]

 [[ 0.8745098   0.8901961   0.88235295]
  [ 0.827451    0.827451    0.827451  ]
  [ 0.8509804   0.8039216   0.81960785]
  ...
  [ 1.          0.8980392   1.        ]
  [ 1.          0.8117647   1.        ]
  [ 0.92941177  0.6862745   0.92941177]]

 ...

 [[-0.827451   -0.7647059  -0.88235295]
  [-0.6784314  -0.6313726  -0.7411765 ]
  [-0.90588236 -0.85882354 -0.96862745]
  ...
  [ 0.7647059   0.7176471   0.54509807]
  [ 0.99215686  0.94509804  0.77254903]
  [ 1.          0.99215686  0.81960785]]

 [

In [16]:
lb = LabelBinarizer() #this will use regression and binary classification algorithm
labels = lb.fit_transform(labels) # this will convert the lables in form of 1,0
print(labels)
labels = to_categorical(labels) #this will convert the label 'wiht mask' and 'without mask' into categorical varible
print(labels)

[[0]]
[[1.]]


In [19]:
data = np.array(data, dtype="float32") #this will convert the labels into array
labels = np.array(labels)
print(labels)


[[1.]]
